import csv

freq = [('get', 326), ('go', 262), ('know', 247), ('im', 229), ('say', 178), ('love', 152), ('make', 144), ('come', 137), ('want', 135), ('take', 125), ('dont', 101),
('keep', 97), ('think', 80), ('see', 68), ('feel', 66), ('let', 64), ('tell', 64), ('live', 59), ('cant', 59), ('find', 57), ('leave', 53), ('sing', 53), ('call', 51),
('theres', 50), ('hold', 50), ('put', 47), ('give', 47), ('look', 46), ('believe', 43), ('hear', 43), ('grow', 42), ('wake', 42), ('forget', 42), ('miss', 42), ('dance', 41),
('ill', 40), ('try', 39), ('write', 37), ('need', 36), ('remember', 35), ('mean', 33), ('set', 33), ('walk', 32), ('gon', 31), ('wont', 30), ('begin', 30), ('na', 30), ('sleep', 29),
('cause', 29), ('save', 28), ('lose', 27), ('hate', 26), ('wan', 26), ('turn', 26), ('start', 26), ('burn', 25), ('use', 25), ('break', 24), ('die', 24), ('hurt', 23),
('fall', 22), ('stay', 22), ('shine', 22), ('stick', 21), ('bring', 21), ('seem', 20), ('kill', 20), ('pull', 19), ('win', 19), ('talk', 19), ('saw', 19), ('kiss', 18),
('confess', 18), ('change', 18), ('wait', 17), ('wear', 17), ('please', 16), ('quit', 16), ('work', 16), ('sit', 15), ('watch', 15), ('play', 15), ('weve', 15), ('follow', 15),
('end', 15), ('stop', 14), ('shes', 14), ('wish', 14), ('become', 14), ('run', 14), ('press', 14), ('cut', 14), ('arent', 14), ('show', 13), ('hope', 13), ('youre', 13),
('fade', 13), ('theyre', 13), ('em', 13), ('stand', 12), ('catch', 12), ('throw', 12), ('scream', 12), ('wave', 12), ('didnt', 11), ('kick', 11), ('thats', 11), ('couldnt', 11),
('matter', 11), ('fill', 11), ('care', 11), ('move', 11), ('retox', 11), ('hell', 11), ('lead', 10), ('swear', 10), ('raise', 10), ('blow', 10), ('choke', 10), ('smell', 10),
('pass', 10), ('sink', 10), ('fight', 10), ('kid', 10), ('taste', 10), ('deserve', 10), ('tear', 10), ('swallow', 9), ('read', 9), ('lock', 9), ('till', 9), ('doesnt', 9),
('fix', 9), ('suppose', 9), ('kinda', 9), ('swing', 9), ('face', 9), ('gate', 9), ('pick', 8), ('teach', 8), ('addict', 8), ('knock', 8), ('tonight', 8), ('cry', 8),
('breathe', 8), ('til', 8), ('shake', 8), ('drive', 8), ('isnt', 8), ('hang', 8), ('pay', 8), ('waste', 7), ('listen', 7), ('blame', 7), ('close', 7), ('deliver', 7),
('roll', 7), ('bury', 7), ('fly', 7), ('relive', 7), ('pour', 7), ('werent', 7), ('open', 7), ('chicago', 7), ('drink', 6), ('lie', 6), ('like', 6), ('remind', 6),
('light', 6), ('hit', 6), ('sound', 6), ('happen', 6), ('send', 6), ('drag', 6), ('trap', 6), ('crush', 6), ('plug', 6), ('sever', 6), ('compose', 6), ('learn', 6),
('wouldnt', 6), ('belated', 6), ('charge', 6), ('shouldve', 6), ('match', 6), ('weave', 6), ('strike', 5), ('prove', 5), ('hide', 5), ('ache', 5), ('dress', 5), ('ask', 5),
('bear', 5), ('hop', 5), ('doom', 5), ('touch', 5), ('flip', 5), ('reset', 5), ('owe', 5), ('wed', 5), ('darling', 5), ('dream', 5), ('id', 5), ('cover', 5),
('drop', 5), ('shin', 5), ('conceal', 5), ('pretend', 5), ('boomerang', 5), ('forever', 5), ('spin', 4), ('fake', 4), ('god', 4), ('shut', 4), ('number', 4), ('cast', 4),
('hijack', 4), ('mr.', 4), ('vent', 4), ('worry', 4), ('star', 4), ('race', 4), ('crash', 4), ('wonder', 4), ('borrow', 4), ('shoot', 4), ('hat', 4), ('destroy', 4),
('fuck', 4), ('whos', 4), ('figure', 4), ('bed', 4), ('apart', 4), ('release', 4), ('fell', 4), ('swim', 4), ('drone', 4), ('medicine', 4), ('smoke', 4), ('boy', 4),
('dust', 4), ('surround', 4), ('curtain', 3), ('compare', 3), ('haunt', 3), ('beg', 3), ('sell', 3), ('build', 3), ('fail', 3), ('solve', 3), ('crawl', 3), ('notice', 3),
('collect', 3), ('trust', 3), ('avoid', 3), ('carry', 3), ('aint', 3), ('tie', 3), ('youd', 3), ('warm', 3), ('check', 3), ('dedicate', 3), ('ruin', 3), ('rain', 3),
('grieve', 3), ('testify', 3), ('windows', 3), ('checker', 3), ('exist', 3), ('list', 3), ('lower', 3), ('sharpen', 3), ('douse', 3), ('rid', 3), ('afraid', 3), ('expect', 3),
('sign', 3), ('align', 3), ('joke', 3), ('laugh', 3), ('slit', 3), ('erase', 3), ('cross', 3), ('paint', 3), ('thank', 3), ('overdose', 3), ('choose', 3), ('drift', 3),
('tight', 3), ('felt', 3), ('oil', 3), ('implode', 3), ('demote', 3), ('suffocate', 3), ('charm', 3), ('procrastinate', 3), ('picture', 2), ('paw', 2), ('fee', 2), ('dare', 2),
('ive', 2), ('force', 2), ('stutter', 2), ('weigh', 2), ('fold', 2), ('lay', 2), ('terrify', 2), ('mind', 2), ('treat', 2), ('realize', 2), ('consider', 2), ('heres', 2),
('drown', 2), ('fan', 2), ('dead', 2), ('scar', 2), ('hunt', 2), ('land', 2), ('beat', 2), ('lean', 2), ('surf', 2), ('convince', 2), ('tap', 2), ('negate', 2),
('mention', 2), ('invite', 2), ('bite', 2), ('bless', 2), ('serve', 2), ('loosen', 2), ('shouldnt', 2), ('react', 2), ('strip', 2), ('protect', 2), ('drain', 2), ('stomp', 2),
('rob', 2), ('mess', 2), ('porch', 2), ('suck', 2), ('stuff', 2), ('gossip', 2), ('sweat', 2), ('said-a', 2), ('mine', 2), ('youll', 2), ('rise', 2), ('hes', 2),
('fit', 2), ('whatever', 2), ('hotel', 2), ('obsess', 2), ('meet', 2), ('time', 2), ('hells', 2), ('bow', 2), ('sneak', 2), ('versus', 2), ('soak', 2), ('speak', 2),
('last', 2), ('twelve', 2), ('bend', 2), ('steal', 2), ('label', 2), ('thatll', 2), ('bargain', 2), ('du', 2), ('disappear', 2), ('trip', 2), ('exchange', 2), ('king', 2),
('anchor', 2), ('chase', 2), ('sweeter', 2), ('box', 2), ('appeal', 2), ('test', 1), ('rag', 1), ('roam', 1), ('dry', 1), ('crust', 1), ('stir', 1), ('trick', 1),
('guild', 1), ('pray', 1), ('attack', 1), ('pete', 1), ('toast', 1), ('bel', 1), ('bottom', 1), ('straight', 1), ('whoa', 1), ('sport', 1), ('apologies', 1), ('stain', 1),
('honeymoon', 1), ('shallow', 1), ('spot', 1), ('defeat', 1), ('hows', 1), ('know-ow', 1), ('stump', 1), ('right', 1), ('red', 1), ('score', 1), ('ring', 1), ('admit', 1),
('lifes', 1), ('compete', 1), ('dive', 1), ('ground', 1), ('somehow', 1), ('ink', 1), ('cue', 1), ('okay', 1), ('trash', 1), ('ooooh', 1), ('overexpose', 1), ('obscure', 1),
('bounce', 1), ('sedate', 1), ('block', 1), ('mark', 1), ('feed', 1), ('receive', 1), ('record', 1), ('mustve', 1), ('spend', 1), ('flick', 1), ('sniff', 1), ('peak', 1),
('worship', 1), ('overrate', 1), ('load', 1), ('select', 1), ('thefalloutboys.com/tour', 1), ('chicago..', 1), ('llamania.com', 1), ('you-', 1), ('planet', 1), ('wash.', 1), ('chew', 1), ('empty', 1),
('dump', 1), ('maul', 1), ('twist', 1), ('harding', 1), ('half-engraved', 1), ('text', 1), ('fob', 1), ('welcome', 1), ('alright', 1), ('relieve', 1), ('elevate', 1), ('plat', 1),
('whats', 1), ('collapse', 1), ('tighten', 1), ('shield', 1), ('diyd', 1), ('shed', 1), ('kerosenes', 1), ('settle', 1), ('nightmare', 1), ('rework', 1), ('snow', 1), ('blind', 1),
('bullet', 1), ('cunning', 1), ('refresh', 1), ('sip', 1), ('carve', 1), ('rancid', 1), ('danzig', 1), ('fixate', 1), ('tick', 1), ('fast', 1), ('aim', 1), ('course', 1),
('arrive', 1), ('hook', 1), ('equip', 1), ('burst', 1), ('count', 1), ('tire', 1), ('judge', 1), ('side', 1), ('comatose', 1), ('friends', 1), ('home', 1), ('explain', 1),
('youve', 1), ('december', 1), ('glow', 1), ('howd', 1), ('defend', 1), ('oh', 1), ('trace', 1), ('splinter', 1), ('memorize', 1), ('act', 1), ('divide', 1), ('tomorrows', 1),
('silver', 1), ('respect', 1), ('rip', 1), ('handle', 1), ('lewis', 1), ('scrutinize', 1), ('pitch', 1), ('buzz', 1), ('restrain', 1), ('scale', 1), ('sing—', 1), ('blur', 1),
('squint', 1), ('dull', 1), ('shrug', 1), ('appear', 1), ('string', 1), ('herald', 1), ('comb', 1), ('stitch', 1), ('correct', 1), ('forgive', 1), ('best', 1), ('calm', 1),
('criticize', 1), ('narrow', 1), ('afford', 1), ('replace', 1), ('theyll', 1), ('organize', 1), ('flaw', 1), ('expose', 1), ('slow', 1), ('dissect', 1), ('mail', 1), ('guide', 1),
('ash', 1), ('wrap', 1), ('pave', 1), ('hire', 1), ('sometimes', 1), ('finish', 1), ('encapsulate', 1), ('yknow', 1), ('wasnt-', 1), ('epic', 1), ('push', 1), ('impress', 1),
('baby', 1), ('rock', 1), ('pack', 1), ('steer', 1), ('wing', 1), ('escape', 1), ('inflate', 1), ('sun', 1), ('draw', 1), ('guess', 1), ('glance', 1), ('stack', 1),
('hush', 1), ('grandstand', 1), ('withstand', 1), ('bat', 1), ('prefer', 1), ('comprehend', 1), ('entitle', 1), ('anywhere', 1), ('heat', 1), ('cool', 1), ('pump', 1), ('poise', 1),
('whove', 1), ('travel', 1), ('condemn', 1), ('ashamed', 1), ('help', 1), ('tip', 1), ('excuse', 1), ('distract', 1), ('plead', 1), ('mistake', 1), ('sorry', 1), ('goin', 1),
('halftime', 1), ('crumble', 1), ('struggle', 1), ('sift', 1), ('split', 1), ('wring', 1), ('fray', 1), ('mummify', 1), ('bloom', 1), ('alter', 1), ('resurrection', 1), ('whine', 1),
('add', 1), ('crack', 1), ('stone', 1), ('analyze', 1), ('gasp', 1), ('control', 1), ('clear', 1), ('couldve', 1), ('join', 1), ('preach', 1), ('rehearse', 1), ('untie', 1),
('bore', 1), ('snore', 1), ('rage', 1), ('ignite', 1), ('spat', 1), ('crunch', 1), ('clip', 1), ('spill', 1), ('outta', 1), ('l', 1), ('heh', 1), ('bicker', 1),
('spark', 1), ('repeat', 1), ('blackmail', 1), ('shadow', 1), ('bust', 1), ('adrenalized', 1), ('-drenalized', 1), ('hadnt', 1)]

with open('frq.csv', 'a') as f:
    writer = csv.writer(f)
    for tup in freq:
        row = [tup[0], tup[1]]
        writer.writerow(row)
    f.close()
